name: "ghp-deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Git
        run: |
          git config --global user.email "lewishamer0@gmail.com"
          git config --global user.name "hamer0"
          git config --global credential.helper store
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run ghp-deploy
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}